name: Build ztail

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Install dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev libxml2-dev
          curl -fsSL https://crystal-lang.org/install.sh | sudo bash

      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install crystal

      - name: Build ztail
        run: |
          crystal build --static --release ztail.cr -o ztail_${{ matrix.os }}_amd64

      - name: Upload ztail artifact
        uses: actions/upload-artifact@v3
        with:
          name: ztail-${{ matrix.os }}-amd64
          path: ztail_${{ matrix.os }}_amd64.exe
          if: matrix.os == 'windows-latest'

      - name: Upload ztail artifact
        uses: actions/upload-artifact@v3
        with:
          name: ztail-${{ matrix.os }}-amd64
          path: ztail_${{ matrix.os }}_amd64
          if: matrix.os == 'ubuntu-latest'
